document.addEventListener('DOMContentLoaded', function () { var detailScript=document.createElement('script');detailScript.src='js/admin-request-details.js';document.body.appendChild(detailScript);
  var loginPanel=document.getElementById('loginPanel'), dashboard=document.getElementById('dashboard'), loginStatus=document.getElementById('loginStatus'), adminStatus=document.getElementById('adminStatus'), requests=[], statuses=['PENDING','UNDER_REVIEW','PROCESSING','APPROVED','COMPLETED','REJECTED','CANCELLED'];
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function call(url,opt){return fetch(url,Object.assign({credentials:'same-origin'},opt||{})).then(function(r){return r.text().then(function(t){var d={};try{d=t?JSON.parse(t):{};}catch(_){d={error:t};}if(!r.ok)throw new Error(d.error||'Request failed.');return d;});});}
  function label(v){return String(v||'').replace(/_/g,' ').toLowerCase().replace(/\b\w/g,function(c){return c.toUpperCase();});}
  function showPanel(name){document.querySelectorAll('.admin-panel').forEach(function(p){p.hidden=p.dataset.section!==name;});document.querySelectorAll('.admin-nav button').forEach(function(b){b.classList.toggle('active',b.dataset.panel===name);});if(name!=='requests'&&name!=='dashboard') loadCms(name);}
  document.querySelectorAll('.admin-nav button').forEach(function(b){b.addEventListener('click',function(){showPanel(b.dataset.panel);});});
  function loadRequests(){return call('/api/admin-requests').then(function(d){requests=d.requests||[];renderRequests();}).catch(function(){adminStatus.textContent='Unable to load requests. Please try again.';adminStatus.className='form-status error';requests=[];renderRequests();throw new Error('request-load-failed');});}
  function renderRequests(){var q=document.getElementById('requestSearch').value.toLowerCase(), f=document.getElementById('statusFilter').value, list=requests.filter(function(x){return(!q||[x.request_id,x.customer_name,x.phone,x.email,x.service_type].join(' ').toLowerCase().includes(q))&&(!f||x.status===f);});list.sort(function(a,b){return(document.getElementById('sortOrder').value==='oldest'?1:-1)*(new Date(a.created_at)-new Date(b.created_at));});var counts={};requests.forEach(function(x){counts[x.status]=(counts[x.status]||0)+1;});document.getElementById('stats').innerHTML=['Total Requests'].concat(statuses).map(function(k){return '<div class="admin-stat"><strong>'+ (k==='Total Requests'?requests.length:counts[k]||0)+'</strong><span>'+label(k)+'</span></div>';}).join('');document.getElementById('requestList').innerHTML=list.map(function(x){return '<article class="admin-request"><div><strong>'+esc(x.request_id)+'</strong><span>'+esc(x.customer_name)+' · '+esc(x.service_type)+'</span><small>'+esc(x.phone)+' · '+esc(x.email)+'</small><small>Submitted '+new Date(x.created_at).toLocaleString()+'</small></div><label>Status<select data-status="'+esc(x.request_id)+'">'+statuses.map(function(s){return '<option '+(s===x.status?'selected':'')+'>'+s+'</option>';}).join('')+'</select></label><label>Customer-facing note<textarea data-customer="'+esc(x.request_id)+'">'+esc(x.customer_note)+'</textarea></label><label>Private admin note<textarea data-admin="'+esc(x.request_id)+'">'+esc(x.admin_notes)+'</textarea></label><div class="admin-request-actions"><button class="btn btn-primary" data-save-request="'+esc(x.request_id)+'">Update Request</button></div></article>';}).join('')||'<p class="form-status">No requests match these filters.</p>';}
  document.getElementById('requestList').addEventListener('click',function(e){var b=e.target.closest('[data-save-request]');if(!b)return;var c=b.closest('.admin-request'),id=b.dataset.saveRequest;b.disabled=true;call('/api/admin-requests',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({requestId:id,status:c.querySelector('[data-status]').value,customerNote:c.querySelector('[data-customer]').value,adminNotes:c.querySelector('[data-admin]').value})}).then(function(){adminStatus.textContent='Request updated.';return loadRequests();}).catch(function(x){adminStatus.textContent=x.message;b.disabled=false;});});
  ['requestSearch','statusFilter','sortOrder'].forEach(function(id){document.getElementById(id).addEventListener('input',renderRequests);});
  function formObject(form){var o={};new FormData(form).forEach(function(v,k){if(k!=='id')o[k]=v;});form.querySelectorAll('input[type=checkbox]').forEach(function(x){o[x.name]=x.checked;});return o;}
  function loadCms(key){var map={homepage:'homepage',media:'media',portfolio:'portfolio',services:'services'};if(!map[key])return;call('/api/admin-cms?resource='+map[key]).then(function(d){var items=d.items||[];if(key==='homepage')fillForm(document.getElementById('homepageForm'),items[0]||{});if(key==='media')renderCmsList('media',items);if(key==='portfolio')renderCmsList('portfolio',items);if(key==='services')renderCmsList('services',items);}).catch(function(x){adminStatus.textContent=x.message;});}
  function fillForm(form,item){Object.keys(item).forEach(function(k){var el=form.elements[k];if(el)el.type==='checkbox'?el.checked=!!item[k]:el.value=item[k]||'';});}
  function save(key,data,button){button.disabled=true;call('/api/admin-cms',{method:data.id?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(Object.assign({resource:key},data))}).then(function(){adminStatus.textContent='Saved successfully.';loadCms(key);}).catch(function(x){adminStatus.textContent=x.message;}).finally(function(){button.disabled=false;});}
  document.querySelectorAll('[data-save="homepage"]').forEach(function(b){b.addEventListener('click',function(){var d=formObject(document.getElementById('homepageForm'));d.id=document.getElementById('homepageForm').elements.id.value;d.status=b.dataset.status;save('homepage',d,b);});});
  var mediaUrlField=document.querySelector('#mediaForm [name="src"]');if(mediaUrlField)mediaUrlField.required=false;
  ['media','portfolio','services'].forEach(function(key){var form=document.getElementById(key==='media'?'mediaForm':key==='portfolio'?'portfolioForm':'servicesForm'),wrap=document.createElement('div');wrap.className='field';wrap.innerHTML='<label>Publishing status<select name="status"><option value="DRAFT">Draft</option><option value="PUBLISHED">Published</option></select></label>';form.querySelector('.form-grid').appendChild(wrap);});
  ['media','portfolio','services'].forEach(function(key){var form=document.getElementById(key==='media'?'mediaForm':key==='portfolio'?'portfolioForm':'servicesForm');form.addEventListener('submit',function(e){e.preventDefault();var d=formObject(form);d.id=form.elements.id.value;if(key==='media'){var file=document.getElementById('mediaFile').files[0];if(file){if(file.size>3500000||!/^image\/(jpeg|png|webp)$/.test(file.type)){adminStatus.textContent='Use a JPG, PNG or WEBP image under 3.5 MB.';return;}var reader=new FileReader();reader.onload=function(){d.src=reader.result;save(key,d,e.submitter||form.querySelector('button'));};reader.readAsDataURL(file);return;}if(!d.src){adminStatus.textContent='Choose an image file or enter an image URL.';return;}}save(key,d,e.submitter||form.querySelector('button'));});});
  function renderCmsList(key,items){var el=document.getElementById(key+'List');el.innerHTML=items.map(function(x){return '<article class="cms-item"><div><strong>'+esc(x.name||x.title||x.headline||x.src)+'</strong><small>'+esc(x.category||x.section||x.status||'')+'</small></div><div class="cms-item-actions"><button class="btn btn-secondary" data-edit-cms="'+key+'" data-item="'+esc(JSON.stringify(x).replace(/"/g,'&quot;'))+'">Edit</button><button class="btn btn-secondary" data-delete-cms="'+key+'" data-id="'+esc(x.id)+'">Delete</button></div></article>';}).join('')||'<p class="form-status">No items yet.</p>';}
  document.addEventListener('click',function(e){var edit=e.target.closest('[data-edit-cms]'),del=e.target.closest('[data-delete-cms]');if(edit){var key=edit.dataset.editCms,x=JSON.parse(edit.dataset.item),form=document.getElementById(key==='media'?'mediaForm':key==='portfolio'?'portfolioForm':'servicesForm');fillForm(form,x);return;}if(del){if(!confirm('Delete this item?'))return;call('/api/admin-cms',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({resource:del.dataset.deleteCms,id:del.dataset.id})}).then(function(){loadCms(del.dataset.deleteCms);});}});
  document.querySelectorAll('[data-clear]').forEach(function(b){b.addEventListener('click',function(){document.getElementById(b.dataset.clear).reset();document.getElementById(b.dataset.clear).elements.id.value='';});});
  document.getElementById('loginForm').addEventListener('submit',function(e){e.preventDefault();loginStatus.textContent='Signing in…';call('/api/admin-login',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:document.getElementById('adminEmail').value,password:document.getElementById('adminPassword').value})}).then(start).catch(function(x){loginStatus.textContent=x.message;loginStatus.className='form-status error';});});
  function start(){loginPanel.hidden=true;dashboard.hidden=false;loadRequests();}
  document.getElementById('refreshButton').addEventListener('click',function(){loadRequests();});document.getElementById('logoutButton').addEventListener('click',function(){call('/api/admin-logout',{method:'POST'}).then(function(){location.reload();});});
  Promise.all([loadRequests()]).then(start).catch(function(){});
});
