document.addEventListener('DOMContentLoaded', function () {
  var loginPanel = document.getElementById('loginPanel');
  var dashboard = document.getElementById('dashboard');
  var loginStatus = document.getElementById('loginStatus');
  var adminStatus = document.getElementById('adminStatus');
  var requests = [];
  var statuses = ['PENDING', 'UNDER_REVIEW', 'PROCESSING', 'APPROVED', 'COMPLETED', 'REJECTED', 'CANCELLED'];
  function escapeHtml(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (character) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]; }); }
  function labelStatus(value) { return String(value || '').replace(/_/g, ' ').toLowerCase().replace(/\b\w/g, function (character) { return character.toUpperCase(); }); }
  function call(url, options) { return fetch(url, { credentials: 'same-origin', ...(options || {}) }).then(function (response) { return response.text().then(function (text) { var data = {}; try { data = text ? JSON.parse(text) : {}; } catch (_) { data = { error: text }; } if (!response.ok) { throw new Error(data.error || 'Request failed.'); } return data; }); }); }
  function load() { adminStatus.textContent = 'Loading requests...'; adminStatus.className = 'form-status'; return call('/api/admin-requests').then(function (data) { requests = data.requests || []; render(); loginPanel.hidden = true; dashboard.hidden = false; document.getElementById('logoutButton').hidden = false; adminStatus.textContent = ''; }).catch(function (error) { console.error('Admin request loading failed', error.message); if (dashboard.hidden) { loginStatus.textContent = error.message; loginStatus.className = 'form-status error'; } else { adminStatus.textContent = error.message; adminStatus.className = 'form-status error'; } }); }
  function visibleRequests() { var query = document.getElementById('requestSearch').value.trim().toLowerCase(); var filter = document.getElementById('statusFilter').value; var list = requests.filter(function (request) { var haystack = [request.request_id, request.customer_name, request.phone, request.email, request.service_type].join(' ').toLowerCase(); return (!query || haystack.indexOf(query) !== -1) && (!filter || request.status === filter); }); list.sort(function (a, b) { var direction = document.getElementById('sortOrder').value === 'oldest' ? 1 : -1; return direction * (new Date(a.created_at) - new Date(b.created_at)); }); return list; }
  function field(label, value) { return '<div class="detail-field"><dt>' + escapeHtml(label) + '</dt><dd>' + escapeHtml(value || 'Not provided').replace(/\n/g, '<br>') + '</dd></div>'; }
  function showDetails(request) { var details = request.request_details || {}; var html = '<div class="request-details-modal"><div class="request-details-panel"><button class="details-close" type="button" aria-label="Close request details">&times;</button><span class="eyebrow">Complete request</span><h2>' + escapeHtml(request.request_id) + '</h2><h3>Request information</h3><dl class="details-grid">' + field('Status', labelStatus(request.status)) + field('Service', request.service_type) + field('Service Category', request.service_category) + field('Description', request.description) + field('Submission Date', new Date(request.created_at).toLocaleString()) + field('Last Updated', new Date(request.updated_at).toLocaleString()) + '</dl><h3>Customer information</h3><dl class="details-grid">' + field('Full Name', request.customer_name) + field('Phone', request.phone) + field('Email', request.email) + field('Preferred Contact', request.preferred_contact_method) + field('Location', request.location) + field('Address', request.address) + field('State', request.state) + field('LGA', request.lga) + '</dl><h3>All submitted information</h3><dl class="details-grid">' + Object.keys(details).map(function (key) { return field(key, details[key]); }).join('') + '</dl><h3>Private admin note</h3><p class="details-private">' + escapeHtml(request.admin_notes || 'No admin note added.') + '</p></div></div>'; document.body.insertAdjacentHTML('beforeend', html); var modal = document.body.lastElementChild; modal.querySelector('.details-close').addEventListener('click', function () { modal.remove(); }); modal.addEventListener('click', function (event) { if (event.target === modal) modal.remove(); }); }
  function render() { var counts = {}; requests.forEach(function (request) { counts[request.status] = (counts[request.status] || 0) + 1; }); document.getElementById('stats').innerHTML = ['Total Requests'].concat(statuses).map(function (key) { return '<div class="admin-stat"><strong>' + (key === 'Total Requests' ? requests.length : counts[key] || 0) + '</strong><span>' + labelStatus(key) + '</span></div>'; }).join(''); document.getElementById('requestList').innerHTML = visibleRequests().map(function (request) { return '<article class="admin-request"><div><strong>' + escapeHtml(request.request_id) + '</strong><span>' + escapeHtml(request.customer_name) + ' · ' + escapeHtml(request.service_type) + '</span><small>' + escapeHtml(request.phone) + ' · ' + escapeHtml(request.email) + '</small><small>Submitted ' + new Date(request.created_at).toLocaleString() + ' · Updated ' + new Date(request.updated_at).toLocaleString() + '</small></div><label>Status<select data-id="' + escapeHtml(request.request_id) + '">' + statuses.map(function (value) { return '<option value="' + value + '"' + (value === request.status ? ' selected' : '') + '>' + labelStatus(value) + '</option>'; }).join('') + '</select></label><label>Customer-facing note<textarea data-customer-note="' + escapeHtml(request.request_id) + '">' + escapeHtml(request.customer_note || '') + '</textarea></label><label>Private admin note<textarea data-admin-note="' + escapeHtml(request.request_id) + '">' + escapeHtml(request.admin_notes || '') + '</textarea></label><div class="admin-request-actions"><button class="btn btn-secondary details-button" data-details="' + escapeHtml(request.request_id) + '" type="button">View Details</button><button class="btn btn-primary save-request" data-save="' + escapeHtml(request.request_id) + '" type="button">Update Request</button></div></article>'; }).join('') || '<p class="form-status">No requests match the current filters.</p>'; }
  document.getElementById('requestList').addEventListener('click', function (event) { var detailsButton = event.target.closest('[data-details]'); if (detailsButton) { var request = requests.filter(function (item) { return item.request_id === detailsButton.dataset.details; })[0]; if (request) showDetails(request); return; } var saveButton = event.target.closest('[data-save]'); if (!saveButton || saveButton.disabled) return; var id = saveButton.dataset.save; var card = saveButton.closest('.admin-request'); var statusField = card.querySelector('[data-id]'); var customerNoteField = card.querySelector('[data-customer-note]'); var adminNotesField = card.querySelector('[data-admin-note]'); saveButton.disabled = true; saveButton.textContent = 'Updating...'; call('/api/admin-requests', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ requestId: id, status: statusField.value, customerNote: customerNoteField.value, adminNotes: adminNotesField.value }) }).then(function () { adminStatus.textContent = 'Request updated successfully.'; adminStatus.className = 'form-status success'; return load(); }).catch(function (error) { console.error('Admin request update failed', error.message); adminStatus.textContent = error.message; adminStatus.className = 'form-status error'; saveButton.disabled = false; saveButton.textContent = 'Update Request'; }); });
  ['requestSearch', 'statusFilter', 'sortOrder'].forEach(function (id) { document.getElementById(id).addEventListener('input', render); });
  document.getElementById('loginForm').addEventListener('submit', function (event) { event.preventDefault(); loginStatus.textContent = 'Signing in...'; call('/api/admin-login', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email: document.getElementById('adminEmail').value, password: document.getElementById('adminPassword').value }) }).then(load).catch(function (error) { loginStatus.textContent = error.message; loginStatus.className = 'form-status error'; }); });
  document.getElementById('refreshButton').addEventListener('click', load);
  document.getElementById('logoutButton').addEventListener('click', function () { call('/api/admin-logout', { method: 'POST' }).then(function () { location.reload(); }); });
  load();
});
