document.addEventListener('DOMContentLoaded',function(){
  document.querySelectorAll('.faq-list details').forEach(function(item){item.addEventListener('toggle',function(){if(!item.open)return;document.querySelectorAll('.faq-list details[open]').forEach(function(other){if(other!==item)other.removeAttribute('open')});var answer=item.querySelector('p');if(answer&&answer.animate&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){answer.animate([{opacity:0,transform:'translateY(-5px)'},{opacity:1,transform:'translateY(0)'}],{duration:180,easing:'ease-out'})}})});
  var header=document.querySelector('.site-header');
  function headerState(){if(header)header.classList.toggle('is-scrolled',window.scrollY>8)} headerState();window.addEventListener('scroll',headerState,{passive:true});
  document.querySelectorAll('.nav-toggle').forEach(function(button){var nav=document.getElementById(button.getAttribute('aria-controls'));if(!nav)return;button.addEventListener('click',function(){var open=nav.classList.toggle('open');button.setAttribute('aria-expanded',String(open));button.querySelector('i').className=open?'fas fa-times':'fas fa-bars'});nav.querySelectorAll('a').forEach(function(link){link.addEventListener('click',function(){nav.classList.remove('open');button.setAttribute('aria-expanded','false');button.querySelector('i').className='fas fa-bars'})})});
  document.addEventListener('keydown',function(event){if(event.key==='Escape'){document.querySelectorAll('.main-nav.open').forEach(function(nav){nav.classList.remove('open');var button=document.querySelector('[aria-controls="'+nav.id+'"]');if(button){button.setAttribute('aria-expanded','false');button.querySelector('i').className='fas fa-bars';button.focus()}})}});
  var params=new URLSearchParams(window.location.search),form=document.getElementById('contactForm'),status=document.getElementById('formStatus');
  if(params.get('sent')==='1'&&status){status.textContent='Thank you - your request has been sent. We will review it and respond as soon as possible.';status.className='form-status success';history.replaceState({},'',window.location.pathname)}
  if(form){form.addEventListener('submit',function(event){if(!form.checkValidity()){event.preventDefault();status.textContent='Please complete the required fields before sending your request.';status.className='form-status error';form.reportValidity();return}var button=form.querySelector('[type="submit"]');if(form.dataset.submitting==='true'){event.preventDefault();return}form.dataset.submitting='true';button.disabled=true;button.innerHTML='<i class="fas fa-circle-notch fa-spin"></i> Sending...';status.textContent='Sending your request securely...';status.className='form-status'})}
  var cacForm=document.getElementById('cacForm'),cacStatus=document.getElementById('cacStatus'),cacSuccess=document.getElementById('cacSuccess'),cacWhatsappLink=document.getElementById('cacWhatsappLink'),cacStarted=false,uploadStarted=false;
  function sendEvent(name){if(typeof gtag==='function')gtag('event',name)}
  function value(id){var el=document.getElementById(id);return el?el.value.trim():''}
  function setError(el,message){var wrap=el.closest('.field')||el.closest('.upload-card'),err=document.getElementById(el.id+'Error');if(wrap)wrap.classList.toggle('is-invalid',!!message);if(err)err.textContent=message||'';el.setAttribute('aria-invalid',message?'true':'false');if(err)el.setAttribute('aria-describedby',err.id)}
  function validPhone(phone){return /^(\+?234|0)[789][01]\d{8}$/.test(phone.replace(/[\s-]/g,''))}
  function validateFile(input){var file=input.files&&input.files[0],allowed=(input.accept||'').toLowerCase(),max=parseInt(input.dataset.maxSize||'5242880',10),meta=document.getElementById(input.id+'Meta'),previewId=input.dataset.preview,preview=previewId&&document.getElementById(previewId);if(preview){preview.hidden=true;preview.removeAttribute('src')}if(!file){if(meta)meta.textContent='No file selected.';setError(input,'Please upload this required document.');return false}if(file.size<1){setError(input,'This file appears to be empty.');return false}if(file.size>max){setError(input,'Please upload a file not larger than 5 MB.');return false}var ext='.'+(file.name.split('.').pop()||'').toLowerCase(),type=(file.type||'').toLowerCase();if(allowed.indexOf(ext)===-1&&allowed.indexOf(type)===-1){setError(input,'Please choose an accepted file type.');return false}if(meta)meta.textContent=file.name+' - '+(type||ext)+' - '+Math.round(file.size/1024)+' KB';if(preview&&type.indexOf('image/')===0){preview.src=URL.createObjectURL(file);preview.hidden=false}setError(input,'');return true}
  if(cacForm){cacForm.querySelectorAll('input,select,textarea').forEach(function(el){el.addEventListener('input',function(){if(!cacStarted){cacStarted=true;sendEvent('cac_form_started')}if(el.type!=='file')setError(el,'')})});cacForm.querySelectorAll('input[type="file"]').forEach(function(input){input.addEventListener('change',function(){if(!uploadStarted){uploadStarted=true;sendEvent('cac_document_upload_started')}validateFile(input)})});cacForm.addEventListener('submit',function(event){var ok=true;[['cacName','Please enter your full name.'],['cacPhone','Please enter a valid Nigerian phone number.'],['cacEmail','Please enter a valid email address.'],['cacType','Please select CAC Business Name.'],['nameOne','Please enter the first proposed business name.'],['nameTwo','Please enter the second proposed business name.'],['nameThree','Please enter the third proposed business name.'],['nature','Please describe the nature of business.'],['businessAddress','Please enter the business address.'],['state','Please select a state.'],['lga','Please enter the LGA.']].forEach(function(item){var el=document.getElementById(item[0]);if(!el)return;var bad=!el.value.trim()||(el.id==='cacPhone'&&!validPhone(el.value))||(el.type==='email'&&!el.validity.valid);setError(el,bad?item[1]:'');if(bad)ok=false});['passport','ninDocument','signature'].forEach(function(id){var input=document.getElementById(id);if(input&&!validateFile(input))ok=false});if(!ok){event.preventDefault();cacStatus.textContent='Please correct the highlighted fields before submitting.';cacStatus.className='form-status error';var first=cacForm.querySelector('[aria-invalid="true"]');if(first)first.focus();return}var message=['CAC Business Name Registration Request','Name: '+value('cacName'),'Phone: '+value('cacPhone'),'Email: '+value('cacEmail'),'CAC Type: BN — Business Name','Proposed Name 1: '+value('nameOne'),'Proposed Name 2: '+value('nameTwo'),'Proposed Name 3: '+value('nameThree'),'Nature of Business: '+value('nature'),'State: '+value('state'),'LGA: '+value('lga'),'Additional Notes: '+(value('notes')||'None'),'I have submitted my CAC registration request through the ABKAB Smart Solution website.'].join('\n');if(cacWhatsappLink)cacWhatsappLink.href='https://wa.me/2349061222869?text='+encodeURIComponent(message);sendEvent('cac_form_submitted');if(cacSuccess){cacSuccess.hidden=false;sessionStorage.setItem('abkabCacSubmitted','1');sessionStorage.setItem('abkabCacWhatsApp',cacWhatsappLink.href)}});if(sessionStorage.getItem('abkabCacSubmitted')==='1'&&cacSuccess){cacSuccess.hidden=false;if(cacWhatsappLink&&sessionStorage.getItem('abkabCacWhatsApp'))cacWhatsappLink.href=sessionStorage.getItem('abkabCacWhatsApp');sessionStorage.removeItem('abkabCacSubmitted');sessionStorage.removeItem('abkabCacWhatsApp');cacSuccess.scrollIntoView({block:'start'})}if(cacWhatsappLink)cacWhatsappLink.addEventListener('click',function(){sendEvent('cac_whatsapp_clicked')})}
  document.querySelectorAll('[data-filter]').forEach(function(button){button.addEventListener('click',function(){var category=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(function(item){item.classList.toggle('active',item===button)});document.querySelectorAll('.project-card[data-category]').forEach(function(card){card.hidden=category!=='all'&&card.dataset.category!==category})})});
  if('IntersectionObserver'in window&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}})},{threshold:.12});document.querySelectorAll('.service-card,.service-detail,.project-card,.reason,.process-step,.testimonial-empty').forEach(function(item){item.classList.add('reveal');observer.observe(item)})}
});
