document.addEventListener('DOMContentLoaded',function(){
  var header=document.querySelector('.site-header');
  function headerState(){if(header)header.classList.toggle('is-scrolled',window.scrollY>8)} headerState();window.addEventListener('scroll',headerState,{passive:true});
  document.querySelectorAll('.nav-toggle').forEach(function(button){var nav=document.getElementById(button.getAttribute('aria-controls'));if(!nav)return;button.addEventListener('click',function(){var open=nav.classList.toggle('open');button.setAttribute('aria-expanded',String(open));button.querySelector('i').className=open?'fas fa-times':'fas fa-bars'});nav.querySelectorAll('a').forEach(function(link){link.addEventListener('click',function(){nav.classList.remove('open');button.setAttribute('aria-expanded','false');button.querySelector('i').className='fas fa-bars'})})});
  document.addEventListener('keydown',function(event){if(event.key==='Escape'){document.querySelectorAll('.main-nav.open').forEach(function(nav){nav.classList.remove('open');var button=document.querySelector('[aria-controls="'+nav.id+'"]');if(button){button.setAttribute('aria-expanded','false');button.querySelector('i').className='fas fa-bars';button.focus()}})}});
  var params=new URLSearchParams(window.location.search),form=document.getElementById('contactForm'),status=document.getElementById('formStatus');
  if(params.get('sent')==='1'&&status){status.textContent='Thank you — your request has been sent. We will review it and respond as soon as possible.';status.className='form-status success';history.replaceState({},'',window.location.pathname)}
  if(form){form.addEventListener('submit',function(event){if(!form.checkValidity()){event.preventDefault();status.textContent='Please complete the required fields before sending your request.';status.className='form-status error';form.reportValidity();return}var button=form.querySelector('[type="submit"]');if(form.dataset.submitting==='true'){event.preventDefault();return}form.dataset.submitting='true';button.disabled=true;button.innerHTML='<i class="fas fa-circle-notch fa-spin"></i> Sending…';status.textContent='Sending your request securely…';status.className='form-status'})}
  document.querySelectorAll('[data-filter]').forEach(function(button){button.addEventListener('click',function(){var category=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(function(item){item.classList.toggle('active',item===button)});document.querySelectorAll('.project-card[data-category]').forEach(function(card){card.hidden=category!=='all'&&card.dataset.category!==category})})});
  if('IntersectionObserver'in window&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){var observer=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}})},{threshold:.12});document.querySelectorAll('.service-card,.service-detail,.project-card,.reason,.process-step,.testimonial-empty').forEach(function(item){item.classList.add('reveal');observer.observe(item)})}
});
