document.addEventListener('DOMContentLoaded', function () {
  var form = document.getElementById('trackingForm'); var status = document.getElementById('trackingStatus'); var result = document.getElementById('trackingResult'); var currentRequest = null; var cardActions = document.createElement('div'); cardActions.className = 'tracking-card-actions'; cardActions.innerHTML = '<button id="saveTrackingCard" class="btn btn-primary" type="button">Save Tracking Card <i class="fas fa-image"></i></button><button id="shareTrackingCard" class="btn btn-secondary" type="button" hidden>Share <i class="fas fa-share-nodes"></i></button><p id="cardStatus" class="form-status" role="status" aria-live="polite"></p>'; result.appendChild(cardActions);
  form.addEventListener('submit', function (event) {
    event.preventDefault(); if (!form.checkValidity()) { form.reportValidity(); return; }
    status.textContent = 'Checking securely...'; status.className = 'form-status'; result.hidden = true;
    fetch('/api/track-request', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ requestId: document.getElementById('trackingId').value, email: document.getElementById('trackingEmail').value }) }).then(function (response) { return response.json().then(function (data) { if (!response.ok) throw new Error(data.error); return data.request; }); }).then(function (request) {
      currentRequest = request; document.getElementById('resultId').textContent = request.request_id; document.getElementById('resultCustomer').textContent = request.customer_name; document.getElementById('resultService').textContent = request.service_type; document.getElementById('resultStatus').textContent = request.status.replace(/_/g, ' '); document.getElementById('resultCreated').textContent = new Date(request.created_at).toLocaleString(); document.getElementById('resultUpdated').textContent = new Date(request.updated_at).toLocaleString(); updateTimeline(request.status); document.getElementById('cardStatus').textContent = ''; result.hidden = false; status.textContent = '';
    }).catch(function (error) { status.textContent = error.message || 'Tracking is temporarily unavailable.'; status.className = 'form-status error'; });
  });
  function updateTimeline(statusValue) { var active = statusValue === 'NEW' ? 0 : statusValue === 'UNDER_REVIEW' ? 1 : statusValue === 'COMPLETED' ? 3 : 2; document.querySelectorAll('.request-timeline [data-step]').forEach(function (step, index) { step.classList.toggle('is-active', index <= active); step.classList.toggle('is-current', index === active); }); }
  function dateLabel(value) { return new Date(value).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' }); }
  function drawText(context, text, x, y, maxWidth, lineHeight) { var words = String(text).split(' '); var line = ''; words.forEach(function (word) { var test = line ? line + ' ' + word : word; if (context.measureText(test).width > maxWidth && line) { context.fillText(line, x, y); y += lineHeight; line = word; } else line = test; }); if (line) context.fillText(line, x, y); return y; }
  function createTrackingCard(request) { var canvas = document.createElement('canvas'); canvas.width = 1800; canvas.height = 1125; canvas.hidden = true; result.appendChild(canvas); var context = canvas.getContext('2d'); context.fillStyle = '#f7f9fd'; context.fillRect(0, 0, canvas.width, canvas.height); context.fillStyle = '#0c2a76'; context.fillRect(0, 0, canvas.width, 250); context.fillStyle = '#e31a1a'; context.fillRect(0, 250, canvas.width, 14); var logo = new Image(); logo.onload = function () { context.drawImage(logo, 90, 48, 380, 136); renderCard(canvas, context, request); }; logo.onerror = function () { renderCard(canvas, context, request); }; logo.src = 'images/logo.svg'; }
  function renderCard(canvas, context, request) { context.fillStyle = '#ffffff'; context.font = '800 42px Manrope, Arial, sans-serif'; context.fillText('REQUEST TRACKING CARD', 90, 360); context.fillStyle = '#0c2a76'; context.font = '800 68px Manrope, Arial, sans-serif'; context.fillText(request.request_id, 90, 470); context.fillStyle = '#526078'; context.font = '700 27px Inter, Arial, sans-serif'; context.fillText('TRACKING NUMBER', 94, 515); context.fillStyle = '#14213d'; context.font = '800 34px Manrope, Arial, sans-serif'; context.fillText('Service', 90, 630); context.font = '500 34px Inter, Arial, sans-serif'; context.fillText(request.service_type, 330, 630); context.font = '800 34px Manrope, Arial, sans-serif'; context.fillText('Submitted', 90, 710); context.font = '500 34px Inter, Arial, sans-serif'; context.fillText(dateLabel(request.created_at), 330, 710); context.font = '800 34px Manrope, Arial, sans-serif'; context.fillText('Status', 90, 790); context.fillStyle = '#e31a1a'; context.font = '800 38px Manrope, Arial, sans-serif'; context.fillText(request.status.replace(/_/g, ' '), 330, 790); context.fillStyle = '#14213d'; context.font = '800 34px Manrope, Arial, sans-serif'; context.fillText('Last updated', 90, 870); context.font = '500 34px Inter, Arial, sans-serif'; context.fillText(dateLabel(request.updated_at), 330, 870); context.fillStyle = '#526078'; context.font = '500 28px Inter, Arial, sans-serif'; drawText(context, 'Keep this card safe. Use your Tracking Number to track your request.', 90, 985, 1250, 40); context.font = '700 27px Inter, Arial, sans-serif'; context.fillText('www.abkabsmartsolution.site', 90, 1065); var cardStatus = document.getElementById('cardStatus'); cardStatus.textContent = 'Tracking card ready.'; var shareButton = document.getElementById('shareTrackingCard'); shareButton.hidden = !navigator.share; canvas._trackingBlob = null; canvas.toBlob(function (blob) { canvas._trackingBlob = blob; shareButton.onclick = function () { if (!canvas._trackingBlob) return; var file = new File([canvas._trackingBlob], request.request_id + '-tracking-card.png', { type: 'image/png' }); navigator.share({ title: 'ABKAB Request Tracking Card', text: request.request_id, files: [file] }).catch(function () {}); }; }, 'image/png'); }
  document.getElementById('saveTrackingCard').addEventListener('click', function () { if (!currentRequest) return; var cardStatus = document.getElementById('cardStatus'); cardStatus.textContent = 'Generating your tracking card...'; createTrackingCard(currentRequest); setTimeout(function () { var canvas = result.querySelector('canvas:last-of-type'); if (!canvas || !canvas._trackingBlob) { cardStatus.textContent = 'Your card could not be generated. Please try again.'; return; } var link = document.createElement('a'); link.download = currentRequest.request_id + '-tracking-card.png'; link.href = URL.createObjectURL(canvas._trackingBlob); link.click(); setTimeout(function () { URL.revokeObjectURL(link.href); }, 1000); }, 250); });
});